-- Create Table INGREDIENT - Script for MySQL 

DROP TABLE FOOD.INGREDIENT;

CREATE TABLE FOOD.INGREDIENT (
    ID BIGINT PRIMARY KEY,
    ING_NAME VARCHAR(40) NOT NULL,
	ING_DESC VARCHAR(80) NULL,
	UNIT_OF_MEASURE BIGINT NULL,
	PKG_UOM BIGINT NULL,
	UNIT_PRICE DECIMAL(6,2) NULL,
	PKG_PRICE DECIMAL (6,2) NULL,
	IS_RECIPE BOOLEAN DEFAULT FALSE);
	
INSERT INTO FOOD.INGREDIENT VALUES(1,'Flour','All purpose flour',1,1,0.3,3.00,false);
	
SELECT * FROM FOOD.INGREDIENT;